version: '3'

services:
  app:
    build: 
      context: ./container/Python
      dockerfile: DockerFile
    
    container_name: 'ChatApp'
    ports:
      - '8000:8000'
    tty: true

    volumes:
      - ./src:/root/workspace
  
  redis:
    image: redis:latest
    container_name: 'Redis'
    ports:
      - '6379:6379'
    volumes: 
      - ./data/redis:/data